### ISSUE TITLE
Whenever I put MQTT logic in a task, it restarts. If I put it in a void loop(), it works fine

### ISSUE THREAD

**Issue by MagicIoT** [espressif/arduino-esp32#1457]
.

**Comment by copercini** [comment]
it seems to be 2 problems:

1- you should put some delay inside the task loops, otherwise the system tasks will not have a chance to run and this will cause problems, your `loop()` and `while(1)` seems to run without any delay in some cases

2- out os stack on task1:
` xTaskCreatePinnedToCore(task1,"task1",1000,NULL,1,NULL,1);`
1000 seems too low for your code

**Comment by MagicIoT** [comment]
I made the above changes, but still not working.

**Comment by MagicIoT** [comment]
.
