### ISSUE TITLE
[question] ArduinoOTA library

### ISSUE THREAD

**Issue by chegewara** [espressif/arduino-esp32#1495]
Ive been asking on forum, but no response. Is it possible to update with this library like with esp-idf ota or is it only to update with esptool.py/exe and from arduino-ide?

**Comment by lbernstone** [comment]
https://github.com/espressif/arduino-esp32/blob/master/libraries/ArduinoOTA/examples/BasicOTA/BasicOTA.ino

**Comment by chegewara** [comment]
I know that example, but there is no info how to push file from internet or any other way. Anyway thanks.

**Comment by lbernstone** [comment]
I am sorry there is no example that does exactly what you want for your particular purpose.  There are a couple of examples in updater as well, and I'm sure google knows something about sketches with uploading to Webserver, but since that is not included in the codebase atm, it will not have an example here... Please close this issue.

**Comment by chegewara** [comment]
Im not asking about particular example, what i am asking is: is it possible or not?

**Comment by lbernstone** [comment]
Yes. ArduinoOTA is specifically for ArduinoOTA.  Update is a generalized library for upgrading firmware.

**Comment by dronecz** [comment]
You can change and use AWS S3 OTA Update, if you want to update your ESP32 from server on Internet..

**Comment by chegewara** [comment]
Sadly i cant make it work with this library:
https://github.com/me-no-dev/ESPAsyncWebServer
so most likely i will use esp-idf ota.
