### ISSUE TITLE
captiveportal example upload file

### ISSUE THREAD

**Issue by telliottosceola** [espressif/arduino-esp32#1536]
### Hardware:
Board:							?ESP-Wroom-32?
Core Installation/update date:			?26/june/2018?
IDE name:							?Platform.io?
Flash Frequency:					?40Mhz?
Upload Speed:						?115200?

### Description:
Is it possible to upload a file through captive portal?

I'm developing a captive portal interface the user will be prompted with when connecting to the board over softAP.  The idea is for the user to enter network credentials for the network they want the board to connect to and also enter a URL for an HTTPS server to report data to.  The user also needs to load a Cert file to the board for the HTTPS server the board will be connecting to.  I have added <input type="file" id="cert_key" name="cert_key" /> and this works if you load the URL in a standard browser window(click choose file button and a file browser shows up, select the file, click submit, file is stored in SPIFFS and everything works.  However if you click the choose file button in the captive window the file browser does not appear.  Is this just a limitation for captive portal windows?  Is it not possible to have the user upload a file in a captive portal?

**Comment by AishwaryaK24** [comment]
@[telliottosceola](https://github.com/telliottosceola)

I know it's been quite a long time since this issue was post, but by any chance did you find a solution to the above problem? 
I am facing a similar issue and it will would be really helpful if you could link some references for the same.
If not, could you tell me what other approach you preferred for passing the certificate to the device?

Thanks.
