### ISSUE TITLE
Does LEDC provide a way to stop outputing signal.

### ISSUE THREAD

**Issue by wgaylord** [espressif/arduino-esp32#2372]
Does the current api have a way to stop outputting a signal. 

There is currently methods for writing a freq or duty to it but I can't see if I can have it stop outputting. For example to stop playing a tone until I am ready to play another.

**Comment by wgaylord** [comment]
So does this mean this question will never be answered?

**Comment by stickbreaker** [comment]
@wgaylord Multiple methods.  Simplest is to set duty cycle to 0. Depending on how you configured the led channel, the idle state will be low or high.

```c++
ledcWrite(channel,0);
```
Harder method is to detach pin.

```c++
ledcDetachPin(pin);
pinMode(pin,INPUT);
// 0r
ledcDetachPin(pin);
pinMode(pin,OUTPUT);
digitalWrite(pin,LOW); // or high?
```

No one answered because the answer was obvious. 

Chuck.

**Comment by wgaylord** [comment]
Answer was not obvious apparently otherwise this would have be answered and closed when it was made.  Nothing tells me that a 0 as duty means anything like stop. (As 0 just means its not changing)

**Comment by stickbreaker** [comment]
ledc outputs a square wave that has a duty cycle proportional to a value.  if the value is half scale that means the output is "on" half the time and "off" half the time. The higher the value the more "on", the lower, the more "off" so.  

I was snarky because you created an issue without filling out the issue template.  You decided that your effort to the complete the issue template was too onerous.  Yet, you wanted someone else to provide you a free gift of their time and resources to solve your problem.  You did not do any research. the first Google Search [randomNerd](https://randomnerdtutorials.com/esp32-pwm-arduino-ide/), Second, the more authoritative answer [ESP32 Documentation](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/peripherals/ledc.html)

Either one would have answered your question, you did not put out the effort to look.

Chuck.
)

**Comment by janith989** [comment]
what ledc_stop does ? is it for stopping output signal when timer is running ?
