### ISSUE TITLE
Can CameraWebServer & SoftAP run together on same ESP32-Camera?

### ISSUE THREAD

**Issue by CameraWebServer** [espressif/arduino-esp32#2869]
Is it possible to run CameraWebServer and SoftAP on same ESP32-CAMERA?
Want to connect to the SoftAP from SmartPhone - using Chrome ...
Adding this to CameraWebServer in Arduino IDE - does not work.

#include <WiFi.h>
#include <WiFiClient.h>
#include <WiFiAP.h>
...

void setup() {
  Serial.begin(115200);
  Serial.setDebugOutput(true);
  Serial.println();

  WiFi.softAP(ssid, password);
  IPAddress myIP = WiFi.softAPIP();
  Serial.print("AP IP address: ");
  Serial.println(myIP);
  ...

**Comment by podericof** [comment]
Hi there, any progress here ? thank you!

**Comment by me-no-dev** [comment]
there is little to no info in the issue. what happens when you start AP, what happens when you try to connect? Are there any messages in the console? Did you set debug level to something other than None in the menu?

**Comment by fdoljack** [comment]
hi,
This post appears to relate to my question.  I have built camerawebserver and it is running on two devices.  Then I noticed that the both the station and softAP modes are active and the webserver can be connected to either through my wifi LAN or be connecting to ESP-Camera and then connecting to 192.168.4.0.  I really don't want this because any neighbor can then connect to my cameras!!!

**Comment by fdoljack** [comment]
BTW, after opening the browser I can stream by addressing http://192.168.4.0/stream.

**Comment by fdoljack** [comment]
sorry for the correction,  but I can stream by sending http://192.168.4.1:81/stream
