### ISSUE TITLE
LAN8720 init override Auto-Negotiation settings

### ISSUE THREAD

**Issue by GitNik1** [espressif/arduino-esp32#3407]
### Hardware:
Board:					own developed board with esp32-pico-d4 and LAN8720A PHY
Core Installation version:	arduino-esp32 1.0.3
IDE name:				Visual Studio (vmicro)
Flash Frequency:			80Mhz
PSRAM enabled:                     no
Upload Speed:		       115200
Computer OS:                        Windows 10

### Description:
The ETH.begin() overrides the Hardware mode configuration.
Why is it so and how can i initialize the Networks with the real Hardware configuration?
I found some method in the esp-idf there can override the auto-negotiation settings.

### Sketch:
```cpp
void phy_lan8720_power_enable(bool enable)
{
    if (enable) {
        uint32_t data = esp_eth_smi_read(MII_BASIC_MODE_CONTROL_REG);
        data |= MII_AUTO_NEGOTIATION_ENABLE | MII_RESTART_AUTO_NEGOTIATION;
        esp_eth_smi_write(MII_BASIC_MODE_CONTROL_REG, data);
        // TODO: only enable if config.flow_ctrl_enable == true
        phy_mii_enable_flow_ctrl();
    }
}

esp_err_t phy_lan8720_init(void)
{
    ESP_LOGD(TAG, "phy_lan8720_init()");
    phy_lan8720_dump_registers();

    esp_eth_smi_write(MII_BASIC_MODE_CONTROL_REG, MII_SOFTWARE_RESET);

    esp_err_t res1, res2;
    // Call esp_eth_smi_wait_value() with a timeout so it prints an error periodically
    res1 = esp_eth_smi_wait_value(MII_PHY_IDENTIFIER_1_REG, LAN8720_PHY_ID1, UINT16_MAX, 1000);
    res2 = esp_eth_smi_wait_value(MII_PHY_IDENTIFIER_2_REG, LAN8720_PHY_ID2, LAN8720_PHY_ID2_MASK, 1000);

    uint32_t data = esp_eth_smi_read(MII_BASIC_MODE_CONTROL_REG);
    data |= MII_AUTO_NEGOTIATION_ENABLE | MII_RESTART_AUTO_NEGOTIATION;
    esp_eth_smi_write(MII_BASIC_MODE_CONTROL_REG, data);

    ets_delay_us(300);

    // TODO: only enable if config.flow_ctrl_enable == true
    phy_mii_enable_flow_ctrl();

    if (res1 == ESP_OK && res2 == ESP_OK) {
        return ESP_OK;
    } else {
        return ESP_ERR_TIMEOUT;
    }
}
```

**Comment by josephpal** [comment]
I am facing exactly the same problem right now. 

My setup: ESP32-WROVER-B connected to LAN8720A, selfmade PCB, the PHY will be connected transformerless, therefore, Auto-Negotiation has to be disabled.
IDE: Arduino IDE with ESP32 core installed

I want to disable auto-negotiation and don't know whether I have do to this by setting register values (http://ww1.microchip.com/downloads/en/Appnotes/00002190A.pdf, page 3) with Pull-UP/DOWN resistors or by using a provided function of ETH.h. It turns out that regarding this link (https://www.esp32.com/viewtopic.php?t=11873), mode configuration pins will be overwritten.

Thx in advance.
