### ISSUE TITLE
Receive binary data with a BLE characteristic #1240

### ISSUE THREAD

**Issue by WayneKeenan** [espressif/arduino-esp32#3553]
Is this the right way to re-open a closed ticket?

Original ticket: "Receive binary data with a BLE characteristic #1240"

I would like to be able to receive binary data.

`BLECharacteristic` needs to provide a `getDataLength()` method to get the length from its `BLEValue m_value` member variable.

Also `BLEValue` will only support binary data by moving away from solely using the std::string type, as this prevents binary data from being represented internally.

**Comment by WayneKeenan** [comment]
bump

**Comment by Bangybug** [comment]
BLEValue::m_value is also a std::string, so no point in exposing BLEValue from BLECharacteristic. I think you can work with binary values via std::string. 

See how BLEValue::addPart is implemented. It is using std::string as a buffer, just like in the following example:

`
#include <string>
#include <stdio.h>

using namespace std;

int main()
{
    std::string data;
    
    data += std::string("binary0\0", 8);  // 8 characters including trailing zero
    data += std::string("binary1\0", 8);  // another 8 characters

    printf("data size: %zu, length: %zu", data.size(), data.length() );
    // outputs 16

    return 0;
}
`

So you can work with std::string in this style:
`
const std::string &value = pCharacteristic->getValue();
value.data() points to your binary data
value.length() or value.size() will be your data length
`

The only drawback is that there may be an extra copying, because pCharacteristic->getValue  does not return reference.
