### ISSUE TITLE
Update LED_BUILTIN pin for LoLin32

### ISSUE THREAD

**Issue by BlueCoal69** [espressif/arduino-esp32#359]
The LED_BUILTIN is on pin 5 per Wemos pics on https://wiki.wemos.cc/products:lolin32:lolin32

I tested the change to five and it works. pin 2 does not work

**Comment by wemos** [comment]
#362 
I make new pull request today.

**Comment by uribass** [comment]
The LED_BUILTIN in active LOW

**Comment by scottchiefbaker** [comment]
Just to clarify, because this confused... You have to set pin 5 `LOW` to turn the LED on, and `HIGH` if you want to turn it off.

```
digitalWrite(LED_BUILTIN, LOW); // Turn LED ON
```

**Comment by AndrasSzep** [comment]
The built-in LED is on pin 22 (GPIO22)

**Comment by a-w** [comment]
> The built-in LED is on pin 22 (GPIO22)

According to the [schematic](https://www.wemos.cc/en/latest/_static/files/sch_d32_v1.0.0.pdf), the LED is on GPIO5

**Comment by samegens** [comment]
For those late to the party (like me) who stumble upon this page: I just figured out why sometimes the pin for the internal LED is GPIO5 and sometimes it's GPIO22. 
For the regular Lolin32, it seems to be GPIO5. However I can't check that, because I seem to have a ... _drum roll_ ... Lolin32 **Lite**! And indeed on that board the pin for the internal LED is GPIO22, which works on my board. See the pinout here: https://www.espboards.dev/esp32/lolin32-lite/
