### ISSUE TITLE
Support SPIFFS library for Arduino MKR Wifi 1010

### ISSUE THREAD

**Issue by anaouss** [espressif/arduino-esp32#4149]
Hello,

I'm working on web page project with Arduino MKR wifi 1010, I wrote my code HTML and I'm trying to control the pins of my Arduino with this page web, but the spiffs doesn't work on MKRwifi. (I got this error: Error compiling for board Arduino MKR WiFi 1010)

Could you help me ?

Regards,
Thanks in advance,
Anass

**Comment by atanisoft** [comment]
This repository is not suitable for the Arduino MKR WiFi boards. You should use the boards setting as defined in the ide for the board and if you still have issues raise it in the Arduino community forum.

**Comment by harsha7addanki** [comment]
stale yo rude

**Comment by atanisoft** [comment]
@harsha7addanki As noted previously, this repository does not support the Arduino MKR WiFi boards which does not use an Espressif chip. It is based on the ARM Cortex-M0 processor with a u-blox NINA-W102. Nothing in this repository would work on that architecture.

stalebot did the correct thing here by closing an issue that was abandoned by the filer which should have closed it themselves since it was not filed to the correct team/company.
