### ISSUE TITLE
Documenting Recommended Approach to Accessing FreeRTOS capabilities

### ISSUE THREAD

**Issue by lonerzzz** [espressif/arduino-esp32#418]
As the ESP32 is sitting on FreeRTOS, is there a recommended or Arduino consistent manner in which to access the underlying RTOS capabilities? What I see so far are wrappers around specific functionality. If I wanted to access the thread controls, is the most standard approach to create some more wrappers or is the idea to reference the FreeRTOS includes directly when the functionality isn't the standard suite available to an Arduino? The same question holds true for things like queues.

Secondly, would the FreeRTOSConfig.h file need to be modified per project based on included functionality?

Some background on the intent of the solution and accessing the different layers would be helpful.

**Comment by igrr** [comment]
I have been looking into this a while ago, haven't been able to find an existing library providing an object oriented wrapper for FreeRTOS APIs. Implementing such a library is probably more or less straightforward exercise.
Another approach is to write some bindings to allow C++11 threading library to be used on top of FreeRTOS. This is slightly more involved, because you have API constraints on both sides to meet (gthread on the top and FreeRTOS on the bottom), but arguably more useful, as that would bring support for C++11 threading to the ESP-IDF as well.

An alternative (but boring) way which doesn't require any additional work is to use FreeRTOS APIs from Arduino directly.

W.r.t FreeRTOSConfig, it is defined at the moment when ESP-IDF components are compiled (some options there depend on options in the project's sdkconfig).
