### ISSUE TITLE
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)

### ISSUE THREAD

**Issue by chandanpalai** [espressif/arduino-esp32#4278]
I made a custom board using ESP32 WROOM 32U chip. I also have a bread board based test rig on which I've been flashing my test programs. The test rig runs fine with written code. However the custom board throws out the following output on serial monitor.

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 

I'm using ESP32 download tools v3.8.5 for flashing both the custom board and the test rig. What am I doing wrong here? 

N.B. I've already checked all the bin file and their addresses prerequisites and burned them on both on the test rig and custom board. Its only the custom board that's giving me this output

**Comment by chandanpalai** [comment]
Hello, I've tried every troubleshoot option that there is but I'm still stuck at this particular problem. Does this have something to do with the Watchdog timer?

**Comment by libasoles** [comment]
Have you ever solved this issue? (and do you remember how?). It's happening to me when I execute this line:
`BLEDevice::init("");
`

The nodemcu keeps restarting itself:

```
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5816
entry 0x400806ac
```

**Comment by libasoles** [comment]
Hey folks, i found the problem with my code. I don't know if it will be useful to someone in the future. I had this:

```
class App {
public:
    void setup() {
        delay(3000); // power-up safety delay
    }

    void loop() { ... }

private:
    BluetoothCommunicationHandler bluetooth{}; <-- initializing the service as a member variable
};
```

For some reason I don't know (I'm new to c++) that causes the reboot when I wanted to start BLE client.

Changed it to:

```
class App {
public:
    void setup() {
        delay(3000); // power-up safety delay
        BluetoothCommunicationHandler bluetooth{}; <-- guess it should work in constructor too
    }

    void loop() { ... }
};
```

That's it. If anyone has a hint on why that was a problem, I'd like to understand. I initialize other services as member variables and that usually works fine. Is this something I should avoid in c++?

**Comment by atanisoft** [comment]
@libasoles If you are declaring that App class globally and you are doing something in the `BluetoothCommunicationHandler` constructor that requires BLE or other functionality to be usable the system will crash on startup due to the global constructor initialize phase runs prior to IDF/Arduino/etc starting up various peripherals/systems/etc.

You can work around this by declaring it as a pointer and initializing it from inside setup().

**Comment by chandanpalai** [comment]
@libasoles I never found a workaround for the problem, nor could I rectify it. I've sent the hardware for redesign now. I will be posting progress with regards to my issue and how/if it gets resolved. Thank you for posting code based solution to the problem. I tried working with very simple codes could not resolve the problem.

**Comment by 09Kartik04** [comment]
12:58:14.385 -> rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
12:58:14.385 -> flash read err, 1000
12:58:14.385 -> ets_main.c 371

**Comment by 09Kartik04** [comment]
what does it mean

**Comment by mihsu81** [comment]
Having the same issue all of a sudden.

**Comment by NorthernMan54** [comment]
So I spent the day with the same issue after updating my software package from espressif32@3.5.0 to espressif32@6.1.0, and after a fair bit of digging into the issue, found that this line when included within my package ( but not executed ) would trigger the issue `pinMode(16, OUTPUT)`.

I had included this as part of integrating to an SSD1306 oled display, and needed to reset the display as part of connecting to it ( https://github.com/ThingPulse/esp8266-oled-ssd1306/issues/326 ) 

```
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 188777542, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13192
load:0x40080400,len:3028
entry 0x400805e4
ets Jun  8 2016 00:22:57
```

**Comment by etienne07C1** [comment]
I have the very same issue looping over and over on serial:
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000

As it is a board I haven't been using for almost a year, wanted to reflash it but I can't.
Any other experiencing same issue, could it be hardware issue?

**Comment by OptoStocks** [comment]
Very similar issue here : 

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:6608
load:0x40078000,len:14788
ho 0 tail 12 room 4
load:0x40080400,len:3792
csum err:0x7a!=0x34
ets_main.c 384 

This board has been running for 6months, and suddenly, stopped booting.
I hardly can find any relevant information... or explanation...
Can someone give a hint please ? :)

**Comment by gauix4** [comment]
anyone has an idea of this problem because it makes all ESP32 S3 unusable !

**Comment by gargamelonly** [comment]
same here.

**Comment by Shayantika-Dhar** [comment]
yesterday the module was working fine with my code, but when i start using today the same code is giving error and now this is showing 

rst:0x8 (TG1WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13964
load:0x40080400,len:3600
entry 0x400805f0

**Comment by Wismute** [comment]
Had the same problem, but **solved it**:

Turns out that in my case it was NodeMCU PyFlasher that i uploaded .bin with

So I had to use esptool (installed with `pip3 install esptool`) and most importantly specify `-z 0x1000` parameter in flashing command to make it look like that:

`esptool --chip esp32 --port COM4 write_flash -z 0x1000 C:\path\to\ESP32_GENERIC-20231227-v1.22.0.bin`

Don't forget to adjust COM port, path to bin and bin name itself to your values.
The `-z` parameter is an address offset in memory we are flashing, which happens to be crucial.

Perhaps somebody faces that problem because of the same reason as me, hope that helps

**Comment by tuvokki** [comment]
> Had the same problem, but **solved it**:
> 
> Turns out that in my case it was NodeMCU PyFlasher that i uploaded .bin with
> 
> So I had to use esptool (installed with `pip3 install esptool`) and most importantly specify `-z 0x1000` parameter in flashing command to make it look like that:
> 
> `esptool --chip esp32 --port COM4 write_flash -z 0x1000 C:\path\to\ESP32_GENERIC-20231227-v1.22.0.bin`
> 
> Don't forget to adjust COM port, path to bin and bin name itself to your values. The `-z` parameter is an address offset in memory we are flashing, which happens to be crucial.
> 
> Perhaps somebody faces that problem because of the same reason as me, hope that helps

The `-z` parameter solved my issue. Thank you.

**Comment by jpelletier** [comment]
I reproduced the problem with minimal code shown below. Serial library works fine. It seems the problem is located in the SPI library.

`#include <SPI.h>
#include <EthernetESP32.h>

#define SPI_SCK 18
#define SPI_MISO 19
#define SPI_MOSI 23
#define SPI_SS 5
#define SPI_IRQ 26
#define SPI_RESET 27

SPIClass SPI1(HSPI);

void setup() {
  Serial.begin(115200);
  delay(500);
  while (!Serial);
  Serial.println("Serial started");

  SPI1.begin(SPI_SCK,SPI_MOSI,SPI_MISO,SPI_SS);
  Serial.println("SPI started");
}

void loop() {
}
`

**Comment by jpelletier** [comment]
changing delay to 100ms or commenting the delay changes nothing.
