### ISSUE TITLE
Can I use GPIO29?

### ISSUE THREAD

**Issue by williamrowley** [espressif/arduino-esp32#4292]
Is it possible to use GPIO29?

I have a custom board where this pin is available but it is not listed in the source code in driver/gpio.h. I can easily add it to the gpio.h file but think I will also need to modify io_mux_reg.h and potentially others. Has anyone done this?

I'm trying to use this pin in SPI communication. And get the error shown below.

I define the pins as such, and setup the busconfig as shown below. The function that fails is spi_slave_initialize() which is contained in my setup function.

Thanks for any advice.

```cpp

#define GPIO_MOSI GPIO_NUM_29
#define GPIO_MISO GPIO_NUM_19
#define GPIO_SCLK GPIO_NUM_18
#define GPIO_CS   GPIO_NUM_16

//Configuration for the SPI bus
spi_bus_config_t buscfg={
    .mosi_io_num=GPIO_MOSI,
    .miso_io_num=GPIO_MISO,
    .sclk_io_num=GPIO_SCLK,
    .quadwp_io_num = -1,
    .quadhd_io_num = -1,
};

ret=spi_slave_initialize(HSPI_HOST, &buscfg, &slvcfg, 1);

```

### Debug Messages:
```
E (8898) spi: spicommon_bus_initialize_io(186): mosi not valid
```

**Comment by atanisoft** [comment]
@williamrowley GPIO29 is not defined since it does not exist on any of the ESP32 variants that I can find:
ESP32: https://www.espressif.com/sites/default/files/documentation/esp32_datasheet_en.pdf
ESP32-WROVER: https://www.espressif.com/sites/default/files/documentation/esp32-wrover_datasheet_en.pdf
ESP32-WROVER-B: https://www.espressif.com/sites/default/files/documentation/esp32-wrover-b_datasheet_en.pdf
ESP32-PICO-D4: https://www.espressif.com/sites/default/files/documentation/esp32-pico-d4_datasheet_en.pdf
ESP32-S2: https://www.espressif.com/sites/default/files/documentation/esp32-s2_datasheet_en.pdf
ESP32-S2-WROVER: https://www.espressif.com/sites/default/files/documentation/esp32-s2-wrover_esp32-s2-wrover-i_datasheet_en.pdf
