### ISSUE TITLE
Can't get SD to work on ESP-32 CAM

### ISSUE THREAD

**Issue by MassiPi** [espressif/arduino-esp32#4680]
Hello,

### Hardware:
|||||||
|:---|---|---|---|---|---|
|<B>Board</B>|ESP32 CAM - AI THINKER
|<B>Version/Date</B>|2.1.0
|<B>IDE name</B>|Platform.io
|<B>Upload Speed</B>|115200
|<B>Computer OS</B>|Windows 10

### Description:
I'm trying to get SD to work, as seen in tons of online examples, but i always get only:

sdmmc_common: sdmmc_init_ocr: send_op_cond (1) returned 0x107
[E][SD_MMC.cpp:84] begin(): Failed to initialize the card (263). Make sure SD card lines have pull-up resistors in place.      

So i started taking out things from the code, but i reached the end (just the SD mount!) and still got the same error, so i'm over with ideas.

### Sketch: 
```
  #include <Arduino.h>
  #include "SD_MMC.h"

void setup() {
  Serial.begin(115200);
  
  //initialize SD card
  if(!SD_MMC.begin()){
    Serial.println("SD Card Mount Failed");
    return;
  } else {
    Serial.println("SD Card mounted");
    Serial.print("SD Card type: ");
    Serial.println(SD_MMC.cardType());
  }
}

void loop() {
}
```

### Debug Messages:
```
sdmmc_common: sdmmc_init_ocr: send_op_cond (1) returned 0x107
[E][SD_MMC.cpp:84] begin(): Failed to initialize the card (263). Make sure SD card lines have pull-up resistors in place.      
```

**Comment by gthubs** [comment]
Hi! Do you have any modules for pins connected? This may be the cause.

In my case, the problem was in AM312 connected to PIN 13 (so it was pulled to GND).
I have an ESP32-CAM. It worked well for a long time with a memory card without a SD_MMC.h library, but directly via driver/sdmmc_host.h, driver/sdmmc_defs.h...esp_vfs_fat_sdmmc_mount() and etc (1-bit mode).

Recently I wanted to show the microSD memory capacity on OLED display, but could't find any functions for this, the closest was
`sdmmc_card_print_info(stdout, card);`
but my knowledge wasn't enough to figure out how to read stdout (File * Stream) and extract memory size (by the way, if anyone knows the decision please write, I am curious).

In the SD_MMC.H there is a ready function
`SD_MMC.totalBytes()`
But when I rewrote code for use this library (also with 1-bit mode) it turned out that the SD can't be initialized, exactly such errors like you:
```
sdmmc_common: sdmmc_init_ocr: send_op_cond (1) returned 0x107
[E][SD_MMC.cpp:85] begin(): Failed to initialize the card (263). Make sure SD card lines have pull-up resistors in place.
```
Then I discovered that the problem is being fixed if I turn off AM312 from PIN 13 or adding this command:
`pinMode(13, INPUT_PULLUP);`
before
`if(!SD_MMC.begin("/sdcard", true)) {`

Now SD card is initialized without problems, after that I can change the PIN mode to INPUT_PULLDOWN and I can displays the memory capacity by this command
`display.printf("SD total size: %llu MB", SD_MMC.totalBytes()/(1024 * 1024));`

As I understood SD_MMC this is a function-wrapper for low-level work with a memory card because in the file "C:\Users\username\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\libraries\SD_MMC\src\SD_MMC.cpp" I found including sdmmc_host.h, sdmmc_defs.h, and etc, but I could't figure it out, why only SD_MMC library requires adding that line

P.S Sorry for the big comment and bad language
