### ISSUE TITLE
Wifi Manager: Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

### ISSUE THREAD

**Issue by PeterJBurke** [espressif/arduino-esp32#4699]
Make your question, not a Statement, inclusive. Include all pertinent information:

What you are trying to do? Run WifiManager on ESP32 Pico V4
Describe your system( Hardware, computer, O/S, core version, environment).
ESP32 Pico V4
Arduino 1.8.13
Wifi Manager from https://github.com/tzapu/WiFiManager
Describe what is failing.
After the access point directs me to a webpage, the ESP32 crashes.
Show the shortest possible code that will duplicate the error.
WiFiManager wifiManager;
wifiManager.autoConnect("ESP32PicoStatAP");

Show the EXACT error message(it doesn't work is not enough).
*WM: SET AP STA
*WM: 
*WM: Configuring access point... 
*WM: ESP32PicoStatAP
*WM: AP IP address: 
*WM: 192.168.4.1
*WM: HTTP server started
*WM: Request redirected to captive portal
*WM: Handle root
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x400014fd  PS      : 0x00060a30  A0      : 0x800de81f  A1      : 0x3ffb1c30  
A2      : 0x00000020  A3      : 0x0000001c  A4      : 0x000000ff  A5      : 0x0000ff00  
A6      : 0x00ff0000  A7      : 0xff000000  A8      : 0x00000000  A9      : 0x3ffb1b90  
A10     : 0x3ffb1c50  A11     : 0x80000000  A12     : 0x3ffb1c50  A13     : 0x0000ff00  
A14     : 0x00ff0000  A15     : 0xff000000  SAR     : 0x0000000a  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000020  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xffffffff  

Backtrace: 0x400014fd:0x3ffb1c30 0x400de81c:0x3ffb1c40 0x400de843:0x3ffb1c60 0x400dbcbe:0x3ffb1c80 0x4015491e:0x3ffb1ce0 0x400d4b23:0x3ffb1d00 0x400d9375:0x3ffb1d20 0x400d93e2:0x3ffb1d50 0x400d954b:0x3ffb1da0 0x400dc7a9:0x3ffb1df0 0x400dc93a:0x3ffb1e30 0x400d1841:0x3ffb1e80 0x400d19ba:0x3ffb1f80 0x400df2e3:0x3ffb1fb0 0x40089799:0x3ffb1fd0

Rebooting...

**Comment by rennn2002** [comment]
I encountered exactly the same issue with my ESP-WROOM-32E. I used my own PCB board designed for esp and the schematic I referenced was Adafruit HUZZAH32 witch means I placed the same caps and resistors for esp. 
the first thing I tried to solve this problem was to replace the capacitor on the power line with the larger one cause' I thought it might be the hardware issue(not enough current supplied) but turned out that the error keeps occurring with the external stabilized power supply.
The wired thing is that when I upload the same firmware to the original Adafruit HUZZAH32, It works perfectly fine even though the hardware setup is the same.
I'm still puzzling on this issue so let me know if you know anything about this.
