### ISSUE TITLE
Detect if the wifi password is incorrect

### ISSUE THREAD

**Issue by am-canes** [espressif/arduino-esp32#4896]
Board: ESP32 Dev Module
Core Installation version: 1.0.5
IDE name: Platform.io
Flash Frequency: 80Mhz
PSRAM enabled: no
Upload Speed: 115200
Computer OS: Windows 10

Is it possible to detect if ESP32 does not connect to wifi because the password is incorrect?
WiFi.status() only returns WL_DISCONNECTED in this situation.

**Comment by me-no-dev** [comment]
you can have a look here: https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/examples/WiFiClientEvents/WiFiClientEvents.ino

On disconnect a reason is given. You can determine that by checking that reason. I would recommend you to also enable debug to level `Info` so that the some logs are printed and reason is more verbose :)
