### ISSUE TITLE
Weird pgm_read_word implemetation that makes no sense and doesn't compile

### ISSUE THREAD

**Issue by VioletGiraffe** [espressif/arduino-esp32#4982]
`framework-arduinoespressif32\cores\esp32\pgmspace.h` defines `pgm_read_word`, `pgm_read_word` and a couple others in a very odd way:
```
#define pgm_read_word(addr) ({ \
  typeof(addr) _addr = (addr); \
  *(const unsigned short *)(_addr); \
})
```

This is how Adafruit_GFX.cpp is trying to use it:
``` writePixel(x + i, y, pgm_read_word(&bitmap[j * w + i]));```
Naturally, this results in a compilation error: `invalid use of void expression`.
You should either define it as a single expression, or as an inline function.

I fixed the problem by editing my local copy of `pgmspace.h` as follows: `#define pgm_read_word(addr) (*(const unsigned short *)(addr))`
Obviously, this is not a solution because it's not portable, my CI builds will fail.

**Comment by arlohb** [comment]
I had a very similar issue to this, stemming from this exact macro, and found this thread.
For me, I fixed it by switching `-std` from `c++2a` to `gnu++2a` to fix `typeof` not being found.
This is because `typeof` is a GNU extension.

Not sure if this was your original issue, but I thought I'd leave it here in case others run across the same issue that I did.
