### ISSUE TITLE
ESP32 Register Level Programming in Arduino IDE

### ISSUE THREAD

**Issue by Eddy12321** [espressif/arduino-esp32#5526]
### Hardware:

Board:							ESP32 Dev Module
Core Installation version:			1.0.6
IDE name:						Arduino IDE 1.8.15
Flash Frequency:				        80Mhz
PSRAM enabled:                                      no
Upload Speed:				        115200
Computer OS:                                          Windows 10

### Description:
Hello! (Less of a bug, and more of a question about programming)

 I am trying to program my ESP32 using register level programming. I have seen multiple forum posts talking about this issue, but all the posts that I have seen are using the esp-idf for programming. I plan to use the Arduino IDE because that is what the other engineers in my company are used to/familiar with. 

Specifically, I am trying to set my esp32 up as an SPI slave so that it can be controlled by a USB to SPI IC (VNC2 by FTDI). The USB to SPI IC is connected to a magstripe card reader. When a card is swiped, the IC captures the data and sends it the esp32 via SPI. This would probably work with the esp32 as the SPI master, but then it would have to constantly poll the IC to see if a card was read. I would rather the esp32 be able to do other tasks until a card is swiped.

First step, i figure, is to set the esp32 as an SPI slave using the SPI_SLAVE_REG (3FF64038) (I am using HSPI). Bit 30 in this register sets the SPI as either slave or master mode. How do I set this bit directly from Arduino code?

To be clear, I am interesting in how to do register level programming from the Arduino IDE. I do not need to be walked through every step of setting the esp32 as an SPI slave (I can figure that out myself, after some hair pulling). 

Any help is greatly appreciated. Thank you!

**Comment by lbernstone** [comment]
There is no mechanism built into arduino-esp32 to allow you to poke the registers.  However, since arduino-esp32 is just a HAL layer over ESP-IDF, you can use the functionality in ESP-IDF to do so.  You could even use the SPI API in IDF to build an SPI slave.  See the [documentation](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/spi_slave.html) and the [example](https://github.com/espressif/esp-idf/tree/master/examples/peripherals/spi_slave).

**Comment by Eddy12321** [comment]
Gotcha! Will post there. Closing this issue now. Thanks.

**Comment by drws** [comment]
You can easily include assembly instructions in Arduino sketch (for example):

`__asm__ __volatile__ ("nop");`

Shouldn't be hard from here on. You probably need just a small wrapper for getting and setting arbitrary registers. I understand this issue is already resolved. Just wanted to post some additional info in case someone finds it useful.
