### ISSUE TITLE
SerialToTelnet doesn't show everything

### ISSUE THREAD

**Issue by szerwi** [espressif/arduino-esp32#559]
### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:			using this version: 5d927847106f84e4714ee2a50545880b0911c1d8
IDE name:							Arduino IDE
Flash Frequency:					80Mhz
Upload Speed:						115200

### Description:
Code that should be shown via Telnet: https://pastebin.com/45tFBb26
Code that is shown via Telnet: https://pastebin.com/4q5hHJVd

Half of the code isn't shown.

### Sketch:
TelnetToSerial example and code to display on Serial. Serial and Serial1 are set to 115200 speed.

### Debug Messages:
-

**Comment by lonerzzz** [comment]
@szerwi Does this work any differently when you change the baud rate or send your data more slowly?

**Comment by jestebanes** [comment]
Hello, I am working on a similar trouble, writes to serial port are asyncronous and maybe if you are writing too fast the serial buffer overflows.

Try to make the buffer greater
In HardwareSerial.cpp, line 29 you can find the serial buffer size declaration, change to 1024 and try again

Best regards

**Comment by lonerzzz** [comment]
@szerwi Is there an update on this issue? Please provide more information if you need it kept open.

**Comment by everslick** [comment]
This issue is closed, because it looks as if it is not a bug or problem with the ESP32 Arduino core or its support libraries. For general API usage questions or help on specific coding challenges, please visit the [arduino-esp32 Gitter channel](https://gitter.im/espressif/arduino-esp32). If you feel this issue was closed in error, reopen it and comment, why you think this is a bug in the Arduino-Core.
