### ISSUE TITLE
Esp32-c3 Bluetooth communication

### ISSUE THREAD

**Issue by dfrobotjw** [espressif/arduino-esp32#5765]
I want to get an Arduino example of esp32-c3. The function is that one esp32-c3 module sends data through Bluetooth, and the other module receives and prints data through Bluetooth

**Comment by chegewara** [comment]
What is wrong with ALL those examples?
https://github.com/espressif/arduino-esp32/tree/master/libraries/BLE/examples

**Comment by VojtechBartoska** [comment]
@dfrobotjw Can I consider this solved?

**Comment by SuGlider** [comment]
@dfrobotjw 
Please use this 2 examples (BLE client and server):
https://github.com/espressif/arduino-esp32/blob/master/libraries/BLE/examples/BLE_client/BLE_client.ino
https://github.com/espressif/arduino-esp32/blob/master/libraries/BLE/examples/BLE_server/BLE_server.ino

They are marked not to be visible when ESP32-C3 board is selected, but they actually work fine with the C3.
You will need 2 C3 boards, one to run the client and another to run the server. 
Turn on menu option "Core Debug Level" to "Verbose" in order to get BLE log messages and to see what is going on in the boards.
