### ISSUE TITLE
The length of the path and file name is longer than allowed in Windows XP!

### ISSUE THREAD

**Issue by todosko** [espressif/arduino-esp32#5779]
How to install "Arduino-esp32" on Windows XP, so that the longest path and file name are shorter than the allowed length for Windows XP. Can someone describe this process consistently. I think this can be useful for many users.

**Comment by chegewara** [comment]
> I think this can be useful for many users.

Useful? who is using Win XP this days?
Im not sure arduino IDE is supported on win xp, because esp-idf for 99% is not.

**Comment by todosko** [comment]
Arduino works great on Windows XP with both AVR and NORDIC ... There is no such deep nesting of files.
Maybe you should make an option for ESP32 on Windows XP?

**Comment by lbernstone** [comment]
I think that Windows XP, along with all other 32-bit Windows, has been deprecated in v2.0.0. So, here's instructions:
1) Download an iso from [ubuntu](https://cdimage.ubuntu.com/lubuntu/releases/18.04/release/lubuntu-18.04.5-desktop-i386.iso).
2) Burn the image to a usb key
3) Install ubuntu
4) Follow the [linux install instructions](https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html#linux)
5) Profit!!

**Comment by lbernstone** [comment]
Put a usb drive in.
Go into Arduino IDE and set your sketchbook path to the root of that drive.
Install the windows repository (as in the linux instructions above) there.  It will be something like E:\hardware\espressif as the root for your esp32 directory.  That's as short a path as you are going to get.
v2.0.0 still won't work, since the esptool executable is 64-bit only, but you can run 1.0.6
