### ISSUE TITLE
Request: recompile esptool.exe with latest updates in pyserial

### ISSUE THREAD

**Issue by cre8dojo** [espressif/arduino-esp32#693]
This is a request to have esptool.exe (https://dl.espressif.com/dl/esptool-4dab24e-windows.zip) updated/recompiled with latest changes from pyserial: (small changes to 2 files)

https://github.com/WorldException/pyserial/commit/c4dd5a2790ac8482ca5bd8bf7547e96a2259186d

Thanks,
Rey

**Comment by projectgus** [comment]
This would require moving pyserial to an older version (v2.7) not a newer version, as pyserial v3.x no longer supports Windows XP.

The commit linked above is in a third-party fork not in the official pyserial release.

More about this here: https://github.com/pyserial/pyserial/issues/148#issuecomment-239519336

esptool.py only requires pyserial v2.5+ at the moment, so rolling back is possible (for now). However there are probably other bugs fixed in newer pyserial that are not fixed in v2.7, so it may require some consideration from that angle.
