### ISSUE TITLE
Arduino IDE Tools Menu documentation

### ISSUE THREAD

**Issue by Zhu-jiatong** [espressif/arduino-esp32#7724]
### Board

ESP32

### Device Description

ESP32 Dev Module

### Hardware Configuration

Not relevant

### Version

v2.0.6

### IDE Name

VS Code + Arduino IDE

### Operating System

Windows 11

### Flash frequency

80Mhz

### PSRAM enabled

no

### Upload speed

921600

### Description

I happen to notice 2 options in the Arduino IDE Tools Menu - `Arduino Runs On` and `Events Run On`, as shown below. 
![image](https://user-images.githubusercontent.com/98582814/212829488-635af201-7486-4f03-8f94-35f1b1028677.png)
What does these options do?
I do know that there is [documentation](https://espressif-docs.readthedocs-hosted.com/projects/arduino-esp32/en/latest/guides/tools_menu.html#arduino-runs-on) already, but they do not say much.

Does anyone know what they do? Thanks in advance.

### Sketch

```cpp
Not relevant
```

### Debug Message

```plain
Not relevant
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
Since Arduino-ESP32 runs on FreeRTOS, the regular `setup()` and `loop()` are executed inside a task. The first option selects on which core that task runs. WiFi (and other ESP-IDF things) emit events that are also handled inside a specific task. The second option controls where that task is running. Core0 by default handles all WiFi/BT and system tasks, thus we run Arduino by default on Core1 in order to not be in the way of WiFi/BT
