### ISSUE TITLE
Is there a way to enable bluedroid log in the Arduino core

### ISSUE THREAD

**Issue by 0x0fe** [espressif/arduino-esp32#8087]
### Board

ESP32D0WR2

### Device Description

custom 

### Hardware Configuration

no relevant

### Version

v2.0.7

### IDE Name

arduino IDE

### Operating System

windows 10

### Flash frequency

80M

### PSRAM enabled

yes

### Upload speed

921600

### Description

Due to a problem with A2DP sink, i have been asked to enable the bluedroid log, https://github.com/espressif/esp-idf/issues/11169  is it possible to do so in the arduino core? Will the preprocessor flag be taken into account?
If it is not possible to add some flag / define to enable log directly in ARduino core, is it possible to compile it in IDF and move the lib with debug enabled to Arduino core?
Thank you.

### Sketch

```cpp
not relevant
```

### Debug Message

```plain
not relevant
```

### Other Steps to Reproduce

not relevant

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
since everything is already precompiled with log disabled, this would not work by just changing config value. The library/IDF would need to be recompiled with log enabled through the esp32-arduino-lib-builder and imported into Arduino. Alternative way is to use "Arduino as IDF component" and compile your sketch that way with log enabled. Maybe that is the easiest way. Just make sure that you compile against ESP-IDF v4.4.4 to ensure that versions are correct.

**Comment by 0x0fe** [comment]
i see, that is what i suspected, i used IDF directly it was faster.
