### ISSUE TITLE
The Arduino Nano ESP32 lacks of support for FileSystem Configuration (IDFGH-10914)

### ISSUE THREAD

**Issue by mathertel** [espressif/arduino-esp32#8553]
### Is your feature request related to a problem?

For the Arduino Nano ESP32 configuration there are no configuration options.
Especially the File System type and size cannot be specified.

### Describe the solution you'd like.

The board is well specified so Flash Size, Flash Mode, PSRAM Size ... is fixed.
But like with other boards the Partition Scheme should be available for configuration.

as well: "Core Debug Level" and "Erase All Flash Before Sketch Upload" is meaningful.

### Describe alternatives you've considered.

A configuration of the generic ESP32S3 Dev Module might be helpful for experts - but there are very special pin re-assignments for this board (D2-D13, A0-A7)

### Additional context.

There seems to be a default FAT FileSystem defined in the partitions somewhere.

**Comment by me-no-dev** [comment]
Please submit this to [Arduino.cc's fork](https://github.com/arduino/arduino-esp32)

**Comment by mathertel** [comment]
The Arduino fork doesn't have the feature issue enabled.

**Comment by pillo79** [comment]
Hello @mathertel and thanks for this request. As you correctly noted, many of the generic parameters are fixed by the board hardware. In addition, some user-friendly features we have implemented on this board further limit the options that we can leave as fully customizable. 

We will try to address some of your proposals in the next core version however, stay tuned!

**Comment by VojtechBartoska** [comment]
Closing as mentioned PR above have been merged.
