### ISSUE TITLE
Support of Zigbee protocol

### ISSUE THREAD

**Issue by P-R-O-C-H-Y** [espressif/arduino-esp32#8807]
This issue tracks support of Zigbee protocol (supported by ESP32C6 and ESP32H2 chips)

Initial steps:

- [x] Investigate [ESP-IDF Zigbee library](https://components.espressif.com/components/espressif/esp-zigbee-lib) 
- [x] Make the Zigbee and Boss libs available - PR #8844
- [x] Followup [PR](https://github.com/espressif/esp32-arduino-lib-builder/pull/146) for lib-builder
- [x] Test IDF example running inside Arduino
- [x] Write easy to use examples

**Comment by P-R-O-C-H-Y** [comment]
Tasks have been updated.

**Comment by Hedda** [comment]
@P-R-O-C-H-Y Off-topic; just wondering if you might be interested in looking at Zigbee for Tasmota? -> https://github.com/arendst/Tasmota/discussions/20045

For reference, Tasmota's Zigbee2Tasmota (Z2T) implementation already supports Texas Instruments ZNP and Silicon Labs EZSP Zigbee stacks/interfaces with respective Zigbee Coordinator adapter running Zigbee NCP (Network Co-Processor) host firmware:

https://tasmota.github.io/docs/Zigbee/

Tasmota itself is a arduino-esp32 based open source firmware for DIY devices (especially popular for home automation solutions):

https://tasmota.github.io/docs/

PS: While Tasmota itself is mature, the ESP32-C6 support in Tasmota is still experimental, however you can follow its progress here:

https://github.com/arendst/Tasmota/discussions/19350

**Comment by P-R-O-C-H-Y** [comment]
Update: Ported 2 simple Zigbee examples from ESP-Zigbee-SDK (esp-idf) #9024.
Creating a wrapper or a library is not planned for now, so after merging the examples we are closing this issue.

**Comment by fillibar** [comment]
With the Arduino examples, are there any plans to make them able to connect to another hub/controller and not just another esp32c6 acting as a coordinator?

While it looks like that might be possible, at this time they just hang (monitor shows it is stuck at "Network steering was not successful"). This seems very similar to the issue here:
https://github.com/espressif/esp-idf/issues/10662

With the IDF example a heavily revised esp_zb_task seemed to help (also updating the dependencies since the ones for those examples are a bit behind).

Making a similar change to the esp_zb_task in the .ino file did not work even after copying that section from code that works when flashed with the idf.

Another thing that might help is if Serial output was provided for more of the functions. Beyond just an initial bit of information when the ESP32C6 starts up, nothing further is recorded in the Arduino IDE's Serial Monitor (vastly less than what the idf's monitor shows).

**Comment by Hedda** [comment]
> With the Arduino examples, are there any plans to make them able to connect to another hub/controller and not just another esp32c6 acting as a coordinator?

FYI, it seems that Espressif devloper(s) are working on an Zigbee NCP radio library for zigpy (Python based Zigbee framework with Zigvee Stack/CLI abstraction API) so can be used as a Zigbee Coordinator NCP for projects like Home Assistant and Domoticz that depend on zigpy. Check out:

https://github.com/zigpy/zigpy/issues/1052

and

https://github.com/zigpy/zigpy-cli/pull/42

Regardless, you should really be posting any Zigbee related question and requests to Espressif’s ESP Zigbee SDK repository instead:

https://github.com/espressif/esp-zigbee-sdk

https://github.com/espressif/esp-zigbee-sdk/issues

**Comment by fillibar** [comment]
I figured this was the place to post about the Arduino question because this is where I found the links to the Arduino examples.

**Comment by ilker-aktuna** [comment]
@Hedda 
since you asked to write on zigbee sdk repo, I created this issue:
https://github.com/espressif/esp-zigbee-sdk/issues/228

But nobody seems to be interested there...
