### ISSUE TITLE
TIMERG0 wdt_wprotect and wdt_feed ESP32-S2 Not exist

### ISSUE THREAD

**Issue by dzungpv** [espressif/arduino-esp32#9033]
### Board

ESP32-S2

### Device Description

WEMOS S2 MINI V1.0.0

### Hardware Configuration

GPIO 9 and GPIO11 use for hardware Serial1

### Version

v2.0.14

### IDE Name

ESP IDF

### Operating System

Macos 13, Windows 10

### Flash frequency

40Mhz

### PSRAM enabled

yes

### Upload speed

115200

### Description

I migrate from ESP32 to ESP32-S2 but could not build, it show error with TIMERG0 wdt_wprotect and wdt_feed

### Sketch

```cpp
#ifdef ESP32
void feedTheDog()
{
  TIMERG0.wdt_wprotect = TIMG_WDT_WKEY_VALUE;
  TIMERG0.wdt_feed = 1;
  TIMERG0.wdt_wprotect = 0;
}
#endif
```

### Debug Message

```plain
In function 'void feedTheDog()':
/config.h:403:11: error: 'struct timg_dev_t' has no member named 'wdt_wprotect'; did you mean 'wdtwprotect'?
   TIMERG0.wdt_wprotect = TIMG_WDT_WKEY_VALUE;
           ^~~~~~~~~~~~
           wdtwprotect
/config.h:404:11: error: 'struct timg_dev_t' has no member named 'wdt_feed'; did you mean 'wdtfeed'?
   TIMERG0.wdt_feed = 1;
           ^~~~~~~~
           wdtfeed
```
```

**Comment by lbernstone** [comment]
What's the question here?  The timer groups are hardware specific, and part of the ESP-IDF.
https://github.com/espressif/esp-idf/blob/v4.4.6/components/soc/esp32s2/include/soc/timer_group_struct.h

**Comment by dzungpv** [comment]
> What's the question here? The timer groups are hardware specific, and part of the ESP-IDF. https://github.com/espressif/esp-idf/blob/v4.4.6/components/soc/esp32s2/include/soc/timer_group_struct.h

I could not build it show wdt_wprotect and wdt_feed error mean it only available on the ESP32 S1? I also change the description.

**Comment by me-no-dev** [comment]
There is no action for us here. You are talking about hardware registers. The chips have what they have, we can not change the chip design now, can we :) Closing as off topic.

**Comment by wotupfoo** [comment]
@dzungpv a more friendly answer here is that the timer hardware changed from ESP32 to ESP-S2|S3 and even though some stayed the same.

@me-no-dev @lbernstone maybe get off your high horse and instead of dismissing this issue, acknowledge that you broke forward compatibility instead of dismissing this poster.

@dzungpv  here is what happened
TIMERG0 exists on both ESP32 and ESP32-S2|3 but for some unknown reason, Espressif decided to change the names of the registers. Go figure.
So for ESP32 you have

    volatile timg_wdtfeed_reg_t wdtfeed;
    volatile timg_wdtwprotect_reg_t wdtwprotect;

But for ESP32-S2|S3 you have
    uint32_t wdt_feed;                                /*Write any value will feed SWDT*/
    uint32_t wdt_wprotect;                            /*If change its value from default  then write protection is on.*/

So, the header file you're using because you changed to the WEMOS S3 (ESP32-S2) no longer has the registers of the ESP32.
[soc/esp32s2/include/soc/timer_group_struct.h](https://github.com/espressif/esp-idf/blob/v4.4.6/components/soc/esp32s2/include/soc/timer_group_struct.h)
[soc/esp32/include/soc/timer_group_struct.h](https://github.com/espressif/esp-idf/blob/v4.4.6/components/soc/esp32/include/soc/timer_group_struct.h)

**Comment by EvillNooB** [comment]
@wotupfoo thank you for pointing in the right direction 😅

was having the same problem and replacing 

```
  TIMERG0.wdt_wprotect = TIMG_WDT_WKEY_VALUE;
  TIMERG0.wdt_feed = 1;
  TIMERG0.wdt_wprotect = 0;
```

with 
```
 TIMERG0.wdtwprotect.wdt_wkey=1356348065;
 TIMERG0.wdtfeed.wdt_feed = 1;
 TIMERG0.wdtwprotect.wdt_wkey=0;
```
solved the issue
