### ISSUE TITLE
Does any arduino library work for esp32 also?

### ISSUE THREAD

**Issue by OAXP** [espressif/arduino-esp32#911]
Does any arduino library work for esp32 also?

**Comment by Manuauto** [comment]
Yes, many libraries do work.

**Comment by lonerzzz** [comment]
Many do but some may not depending on how tied to the hardware they are.

**Comment by OAXP** [comment]
@lonerzzz  for example this one don't worked or I made a mistake: https://github.com/espressif/arduino-esp32/issues/914

**Comment by everslick** [comment]
This issue is closed, because it looks as if it is not a bug or problem with the ESP32 Arduino core or its support libraries. For general API usage questions or help on specific coding challenges, please visit the [arduino-esp32 Gitter channel](https://gitter.im/espressif/arduino-esp32). If you feel this issue was closed in error, reopen it and comment, why you think this is a bug in the Arduino-Core.
