### ISSUE TITLE
OTA of a new partition table

### ISSUE THREAD

**Issue by meakashrao** [espressif/arduino-esp32#9161]
### Related area

OTA

### Hardware specification

ESP32 Wroom 32E

### Is your feature request related to a problem?

So, a year back some of our products were shipped with min_spiffs.csv and we are very close to hitting the partition space(we are using 90% of the space)
After more analysis, it was figured out that Flash is actually 8MB but we never used the other 4MB more than that defined in the min_spiffs.csv

So, we need a method to update the partition table through OTA, I tried accessing information. There's no official way of doing it,

### Describe the solution you'd like

If it's possible I would like to update the bootloader.bin to look for new partition table if it exists then use it or else us min_spiffs.csv

directly, just updating the partitions.bin might fail and there would be nothing to fall back to. 

### Describe alternatives you've considered

Alternate would be serial upload but that is troublesome because there are devices everywhere in the country

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by me-no-dev** [comment]
Hi @meakashrao. I suggest that you ask this question in ESP-IDF's repo, where all the code and examples that you would need exist. There are ways to alter the partition scheme through the firmware (check if it's the old one and adjust to the new one), but I am not sure if it can be done by OTA. Maybe custom OTA that you will have to handle yourself and implement overwriting the flash at the proper location. AFAIK such things require lower API access to the flash, as higher level functions do protect the region. Bootloader I am pretty sure is out of the question, but you do not need to do it anyway.

Again. such questions will be best answered in ESP-IDF

**Comment by Jason2866** [comment]
The good news it is possible. We do something like this in project Tasmota. Real flash size is detected at boot time and the FS partition (last in partition table!) is enhanced. The partition table is adopted to the new setting too.
This is not possible with official Arduino Framework since it needs writing to flash outside the boundaries allowed for the running firmware (sdkconfig setting `CONFIG_SPI_FLASH_DANGEROUS_WRITE_ALLOWED=y`) this flag is not set in official framework.
To make this possible, functions to build the partition table and writing a valid partition entry (from IDF) has been implemented in Tasmota code (not just a few lines of code...)
Nice feature when using LittleFS enhancing the FS partition this way content keeps intact.

Imho it is feasible that the needed functions could be implemented in Arduino but the question is how many users will use such a feature. Beside the fact that is not "Arduino"

**Comment by meakashrao** [comment]
Hello @Jason2866 Thanks once again to replying to a second query, is this Project Tasmota open source? I would like to get a better idea of how to implement it and then would do it.

**Comment by Jason2866** [comment]
Yes, it is Open Source. Repo https://github.com/arendst/Tasmota

**Comment by meakashrao** [comment]
> Hi @meakashrao. I suggest that you ask this question in ESP-IDF's repo, where all the code and examples that you would need exist. There are ways to alter the partition scheme through the firmware (check if it's the old one and adjust to the new one), but I am not sure if it can be done by OTA. Maybe custom OTA that you will have to handle yourself and implement overwriting the flash at the proper location. AFAIK such things require lower API access to the flash, as higher level functions do protect the region. Bootloader I am pretty sure is out of the question, but you do not need to do it anyway.
> 
> Again. such questions will be best answered in ESP-IDF

Ok. I will ask there. Thank you
