### ISSUE TITLE
FSPI and ESP32-S2

### ISSUE THREAD

**Issue by vincentfenet** [espressif/arduino-esp32#9210]
### Board

ESP32-S2FN4R2

### Device Description

none

### Hardware Configuration

none

### Version

latest master (checkout manually)

### IDE Name

none

### Operating System

none

### Flash frequency

none

### PSRAM enabled

yes

### Upload speed

115200

### Description

looks like [this](https://github.com/espressif/arduino-esp32/blob/d14873ab8a95b86c8f38ceaed01642dd2909dcb3/cores/esp32/esp32-hal-spi.h#L35) is not vaild for ESP32S2.

when i look at the ESP32S2 documentation:
Ports of embedded flash correspond to pins of ESP32-S2FH2 and ESP32-S2FH4 as follows:
–CS# = SPICS0
–DI = SPID
–DO = SPIQ
–CLK = SPICLK
–WP# = SPIWP
–HOLD# = SPIHD
Ports of embedded PSRAM correspond to pins of ESP32-S2FN4R2 and ESP32-S2R2 as follows:
–CE# = SPICS1
–SI/SIO0 = SPID
–SO/SIO1 = SPIQ
–SCLK = SPICLK
–SIO2 = SPIWP
–SIO3 = SPIHD
These pins are not recommended for other uses

could you please fix this ?
thanks,
vincent

### Sketch

```cpp
none
```

### Debug Message

```plain
none
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by lbernstone** [comment]
Please explain better what the issue is, and what you believe the fix would be.  The [default for SPI is to use HSPI](https://github.com/espressif/arduino-esp32/blob/master/libraries/SPI/src/SPI.h#L64), which will not use the SPI flash pins.  However, they are available if you have a valid use case.

**Comment by SuGlider** [comment]
>These pins are not recommended for other uses
could you please fix this ?
thanks,
vincent

I don't see anything to fix. Please let me know if you disagree and explain how is it wrong.

**Comment by vincentfenet** [comment]
sorry, i was speaking about the comment: "SPI bus attached to the flash (can use the same data lines but different SS)"
on ESP32S2 the flash is not attached to the FSPI bus

**Comment by SuGlider** [comment]
> sorry, i was speaking about the comment: "SPI bus attached to the flash (can use the same data lines but different SS)" on ESP32S2 the flash is not attached to the FSPI bus

Yes, correct, but FSPI (ESP32-S2 SPI2) can be used to control external flash / psram, if necessary. 
Arduino SPI class is just for General Purpose use with a MISO/MOSI/CLK/CS pins.

ESP32-S2N4R2 uses SPI0 for controlling internal SoC Flash (4MB) and the SPI1 for controlling the internal SoC (2MB) PSRAM.
The GPIOs for those 2 memories are not exposed to users in the chip.

In order to use SPI2 (Arduino FSPI) to access external memory, I'd suggest to use IDF calls instead and not use Arduino SPI Class.
Please check this discussion: https://github.com/espressif/arduino-esp32/issues/8479
A possible code for your application may be related to https://github.com/espressif/arduino-esp32/issues/8479#issuecomment-1664937971

IDF Flash SPI API is described here:
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/spi_flash/index.html 
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/spi_flash/spi_flash_optional_feature.html

Related IDF examples:
https://github.com/espressif/esp-idf/tree/master/examples/storage/custom_flash_driver
https://github.com/espressif/esp-idf/tree/master/examples/storage/ext_flash_fatfs

### In order to use IDF + Arduino, it would be necessary to create an `Arduino as IDF Component Application`.

**Comment by vincentfenet** [comment]
i have no problem using it, it's just that the comments are wrong.

I expect something like this:

```
#define FSPI  1 //SPI bus. for ESP32S2: for external flash only (can use the same data lines but different SS)
#define HSPI  2 //SPI bus for ESP32S2: external flash or device (normally mapped to pins 12 - 15, but can be matrixed to any pins)
#if CONFIG_IDF_TARGET_ESP32
#define VSPI  3 //SPI bus for ESP32S2: device only (normally attached to pins 5, 18, 19 and 23, but can be matrixed to any pins)
```

**Comment by SuGlider** [comment]
OK. It sounds good for the ESP32-S2. I'll change the code to reflect this description and commentaries.
I'd just change it to say "external memory" instead of "external flash" given that it can be used for psram as well.

**Comment by SuGlider** [comment]
We shall also consider that those code lines about FSPI and HSPI are valid for ESP32 too.

**Comment by SuGlider** [comment]
@vincentfenet  Check the changes in https://github.com/espressif/arduino-esp32/pull/9216/files and let me know if you agree to them. Thanks!

**Comment by vincentfenet** [comment]
i totaly agree with this. thanks for your cooperation !
