### ISSUE TITLE
Hardware accelerated encryption. Is there an example on how to use this function?

### ISSUE THREAD

**Issue by cotestatnt** [espressif/arduino-esp32#999]
I would like to have access to the hardware accelerated encryption with Arduino core.
Someone has a working example?

**Comment by lbernstone** [comment]
What would you like to do with it? The only place it is exposed in arduino-esp32 at the moment is in WiFiClientSecure.  If you want something else, you will need to use the ESP-IDF and mbedTLS directly. https://github.com/espressif/esp-idf/tree/master/components/mbedtls/port

**Comment by everslick** [comment]
This issue is closed, because it looks as if it is not a bug or problem with the ESP32 Arduino core or its support libraries. For general API usage questions or help on specific coding challenges, please visit the [arduino-esp32 Gitter channel](https://gitter.im/espressif/arduino-esp32). If you feel this issue was closed in error, reopen it and comment, why you think this is a bug in the Arduino-Core.
